GET http://localhost:5001/api/steps
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZhNjExMjJjNGU4ZTZiYjY1NzJkY2MiLCJuYW1lIjoiU2FsdmkiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjUyMjAzNjY2LCJleHAiOjE2NTI4MDg0NjZ9.9nhQwVSjRIY-gIHO2QcypxTDsbeQZAMOH9p1LKvx2hE